
# CREANDO NOMBRE Y CONTRASEÑA DE USUARIO
CREATE USER 'user_ventas'@'localhost' IDENTIFIED BY 'holaCOMO';

# ASIGNANDO PRIVILEGIOS
GRANT ALL PRIVILEGES ON ventas.* TO 'user_ventas'@'localhost';
FLUSH PRIVILEGES;
