use ventas;

# TABLA QUE TENDRA INFORMACION DE LOS ESTADOS DISPONBILES 
CREATE TABLE estado(
	id_estado INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(15) NOT NULL
);

# TENDRA LOS REGISTRO DE LAS PROVINCIAS DISPONIBLES PARA DIRECCION
CREATE TABLE provincia(
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(35) NOT NULL,
    estado_id INT NOT NULL DEFAULT 1,
    CONSTRAINT FK_provincia_estado_idEstado FOREIGN KEY (estado_id) REFERENCES estado(id_estado)
);