
# CREANDO NOMBRE Y CONTRASEÑA DE USUARIO PARA LA BD
CREATE USER 'user_ventas'@'localhost' IDENTIFIED BY 'holaCOMO';

# ASIGNANDO PRIVILEGIOS
GRANT ALL PRIVILEGES ON ventas.* TO 'user_ventas'@'localhost';
FLUSH PRIVILEGES;

# USUARIO QUE UTILIZARAN LOS ADMINISTRADORES
CREATE USER 'administrador'@'localhost' IDENTIFIED BY '1234';

GRANT SELECT, INSERT, UPDATE, EXECUTE ON ventas.* TO 'administrador'@'localhost';
FLUSH PRIVILEGES;

# USUARIO QUE UTILIZARAN CLIENTES
CREATE USER 'cliente'@'localhost' IDENTIFIED BY 'hola';
-- LOS PRIVILEGIOS LO ASIGNARA DESPUES DE CREAR LAS TABLAS

#GRANT SELECT, INSERT, UPDATE, EXECUTE ON ventas.* TO 'administrador'@'localhost';
#FLUSH PRIVILEGES;
